spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: ywx041108
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
    port: 8080


